Traceback (most recent call last):
  File "CausalBertInference.py", line 7, in <module>
    cb = CausalBert()
TypeError: 'module' object is not callable
